#!/usr/bin/env python3
"""
Wrapper module to provide leaderboard snapshot for PV758
to be used in citi_bike_app.py
"""

import csv
from pathlib import Path

# Path to CSV generated by your scraper
CSV_PATH = Path(__file__).parent / "ns143_points.csv"
TARGET_ID = "NS143"

def snapshot_pv758():
    """
    Reads the latest row for PV758 from the CSV and returns an object
    compatible with citi_bike_app.py
    """
    if not CSV_PATH.exists():
        return None  # CSV doesn't exist yet

    with open(CSV_PATH, newline="") as f:
        reader = list(csv.DictReader(f))
        if not reader:
            return None

    # Look for latest row with TARGET_ID
    for row in reversed(reader):
        if row.get("id") == TARGET_ID:
            class LB:
                rank = row.get("rank")
                points = int(row.get("points", 0))
                points_behind_first = 0  # optional
                fetched_at = f"{row.get('date')} {row.get('time')}"
            return LB()

    return None
